# fabric引擎端口
BaasFabricEnginePort: 30001
# baas 的根目录
BaasRootPath: /root/telbaas/TelBaaS/baas-fabricEngine
# nfs server ip
BaasNfsServer: 192.168.1.13
# k8s引擎地址
BaasKubeEngine: http://139.198.15.29:30002
# 在baas根目录下nfs共享目录
BaasNfsShared: baas-nfsshared
# 在baas根目录下fabric k8s模板目录
BaasTemplate: fabric-template
# 保存chaincode的gopath下的src目录
BaasChaincodeGithub: github.com/baaschaincodes
# 共识排序参数
OrdererBatchTimeout: 1s
OrdererMaxMessageCount: 10
OrdererAbsoluteMaxBytes: 99 MB
OrdererPreferredMaxBytes:  512 KB
